version: '3.3'

networks:
    default:
        external:
            name: sentimental_network

services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
    - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - USE_LIGHT_IMAGE=1
      - PORT_WEB_UI=9080